version: '3.8'
services:
  backend:
    restart: always
    build:
      args:
        user: be-user
        uid: 1000
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./API:/var/www/html
    depends_on:
      - db

  # frontend:
  #   restart: always
  #   build:
  #     context: ./FE
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./FE:/usr/src/app
  #   depends_on:
  #     - backend

  db:
    image: mysql:latest
    container_name: mysql-container
    logging:
      options:
        max-size: 10m
    environment:
      MYSQL_DATABASE: darkside_code_test
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: user
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./API/docs/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: user
    ports:
      - 80:80
    links:
      - db